{% set name = "empyrical-reloaded" %}
{% set version = "0.5.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 40ece30b61bbeb03d1a20d64e803a8715da56dbec47d74dcf9df5fffb32b1b2d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy >=1.9.2
    - bottleneck >=1.3.0
    - pandas >=1.0.0
    - scipy >=0.15.1
    - pandas-datareader >=0.4
    - yfinance >=0.1.63

test:
  imports:
    - empyrical

about:
  home: https://pypi.org/project/empyrical-reloaded/
  summary: empyrical computes performance and risk statistics commonly used in quantitative finance
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - stefan-jansen
